//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKKK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widok_Wizyty
    {
        public System.DateTime Czas_rozpoczecia { get; set; }
        public System.DateTime Czas_zakonczenia { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string NumerSali { get; set; }
        public string Imie_Nazwisko { get; set; }
        public string Specjalizacja { get; set; }
    }
}
