//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKKK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyta
    {
        public int Id { get; set; }
        public System.DateTime CzasRozpoczecia { get; set; }
        public System.DateTime CzasZakonczenia { get; set; }
        public int Pacjent { get; set; }
        public int Sala { get; set; }
        public int Lekarz { get; set; }
    
        public virtual Lekarz Lekarz1 { get; set; }
        public virtual Pacjent Pacjent1 { get; set; }
        public virtual Sala Sala1 { get; set; }
    }
}
